name: Sync Upstream

on:
  workflow_dispatch: # allow manually trigger the action

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Job-level permissions configuration starts here
      contents: write # 'write' access to repository contents
      pull-requests: write # 'write' access to pull requests
    env:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
      MYSTEN_SPREEDSHEET_ID: ${{ secrets.MYSTEN_SPREEDSHEET_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Use the GitHub checkout action to checkout code

      - name: Get Allow List
        env:
          TOKEN: ${{ secrets.repo_token }}
        run: |
          curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/acct/repo2/main/test.json

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Auto-update from script" || echo "No changes to commit"
          git push
